version: '3'

services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 7100:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - 8000:5000
    environment:
      PORT: 5000
      MONGODB_DATABASE_URL: 'mongodb://root:vEcsh9dFTdNa66V8@db:27017/paycheck?authSource=admin'
      PATH_IMAGE: /home/paycheck_dev/image-files
      PATH_PAYMENT: /home/paycheck_dev/invoice-files
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - image-files:/home/paycheck_dev/image-files
      - invoice-files:/home/paycheck_dev/invoice-files
  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vEcsh9dFTdNa66V8
      MONGO_INITDB_DATABASE: paycheck
    ports:
      - 31007:27017
    volumes:
      - db:/data/db
    networks:
      - backend

volumes:
  db:
  image-files:
  invoice-files:

networks:
  backend: